server:
  port: 999
  shutdown: graceful

spring:
  application:
    name: spring-boot-websocket
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:5306/mydb?useSSL=false&serverTimezone=UTC
    username: root
    password: 1234
  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true
    locations: classpath:db/migrations

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.web.servlet: DEBUG
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.messaging: DEBUG
    com.natsukashiiz.sbws: DEBUG
